version: '3.2'

services:
  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: spigreen_nginx
    volumes:
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./web:/var/www/html"
      - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
    ports:
      - "80:80"
      - "443:443"
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    depends_on:
      - php-fpm
      - db
  php-fpm:
    image: nanoninja/php-fpm
    container_name: spigreen_php_fpm
    restart: always
    volumes:
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./web:/var/www/html"
#  composer:
#    image: composer:${COMPOSER_VERSION}
#    container_name: spigreen_composer
#    volumes:
#      - "./web/backend:/app"
#    working_dir: /app
#    command: install
#  node:
#    image: node:${NODE_VERSION}
#    container_name: spigreen_node
#    volumes:
#      - "./web/frontend:/app"
#    working_dir: /app
#    command: "npm install"
  db:
    image: mysql:${MYSQL_VERSION}
    container_name: spigreen_mysql
    healthcheck:
      test: "exit 0"
    env_file:
      - .env_mysql
    ports:
      - "3306:3306"
    command: mysqld --sql_mode=""
    restart: always
